### ISSUE TITLE
Discord WebSocket requesting client reconnect

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#10]
```
[discord-websockets.c:103] _ws_on_close_cb()
CLOSE=1001 46 bytes 'Discord WebSocket requesting client reconnect.'
* Operation timed out after 6517351 milliseconds with 7102 bytes received
* SSL: EOF without close notify
```

**Comment by mlite** [comment]
the message is from the latest test-ws.

**Comment by LucasMull** [comment]
We are still lacking resume logic as of this moment, there are many scenarios that could be responsible for the disconnection. I don’t think its a bug (unless you are getting this consistently), since the on_close is an action triggered by normal websockets interaction.

**Comment by LucasMull** [comment]
One thing that captures um attention though is this particular message:

```
* SSL: EOF without close notify
```
Do you know the meaning behind it?

**Comment by mlite** [comment]
> One thing that captures um attention though is this particular message:
> 
> ```
> * SSL: EOF without close notify
> ```
> 
> Do you know the meaning behind it?

I haven't been able to find out the cause yet.  But the message came after on_close is called.  So it should not be the cause for reconnecting.

**Comment by mlite** [comment]
> We are still lacking resume logic as of this moment, there are many scenarios that could be responsible for the disconnection. I don’t think its a bug (unless you are getting this consistently), since the on_close is an action triggered by normal websockets interaction.

Understood.  I was wondering how we can know what caused the server to send on_close event.  If we want to tell other people our lib is easy to debug, more diagnostic information will be really helpful.  I'm more interested in knowing the cause than fixing this problem.  How can we collect information to provide more diagnostic information?

**Comment by LucasMull** [comment]
> > We are still lacking resume logic as of this moment, there are many scenarios that could be responsible for the disconnection. I don’t think its a bug (unless you are getting this consistently), since the on_close is an action triggered by normal websockets interaction.
> 
> 
> 
> Understood.  I was wondering how we can know what caused the server to send on_close event.  If we want to tell other people our lib is easy to debug, more diagnostic information will be really helpful.  I'm more interested in knowing the cause than fixing this problem.  How can we collect information to provide more diagnostic information? 
> 
> 

I agree. Once the echo bot is done I think we should focus on polishing the established code and adding useful tools such as proper error diagnostics, what do you think?

**Comment by mlite** [comment]
that's a good plan.

**Comment by mlite** [comment]
The bot was terminated after running for a while.   In the abort message, there is a `Operation timed out` message.   I was wondering if this is caused by heartbeats were not sent correctly. 
```
[discord-websockets.c:111] _ws_on_close_cb()
        CLOSE=1001 46 bytes 'Discord WebSocket requesting client reconnect.'
* Operation timed out after 1219907 milliseconds with 2311 bytes received
* SSL: EOF without close notify
```

**Comment by mlite** [comment]
The code 1001 from https://tools.ietf.org/html/rfc6455#section-7.4.1

```
1001

      1001 indicates that an endpoint is "going away", such as a server
      going down or a browser having navigated away from a page.
````

**Comment by LucasMull** [comment]
> The bot was terminated after running for a while.   In the abort message, there is a `Operation timed out` message.   I was wondering if this is caused by heartbeats were not sent correctly. 
> 
> ```
> 
> [discord-websockets.c:111] _ws_on_close_cb()
> 
>         CLOSE=1001 46 bytes 'Discord WebSocket requesting client reconnect.'
> 
> * Operation timed out after 1219907 milliseconds with 2311 bytes received
> 
> * SSL: EOF without close notify
> 
> ```

I'm not sure. But by the error code received we know that its a cloudflare issue.

See: https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1001

And a similar issue (3y old): https://github.com/Just-Some-Bots/MusicBot/issues/1574

It seems to be on their end.

**Comment by LucasMull** [comment]
If it were heartbeats being sent incorrectly we would be getting one of the [Discord opcodes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes), I believe.

**Comment by mlite** [comment]
> > The bot was terminated after running for a while.   In the abort message, there is a `Operation timed out` message.   I was wondering if this is caused by heartbeats were not sent correctly.
> > ```
> > 
> > [discord-websockets.c:111] _ws_on_close_cb()
> > 
> >         CLOSE=1001 46 bytes 'Discord WebSocket requesting client reconnect.'
> > 
> > * Operation timed out after 1219907 milliseconds with 2311 bytes received
> > 
> > * SSL: EOF without close notify
> > ```
> 
> I'm not sure. But by the error code received we know that its a cloudflare issue.
> 
> See: https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1001
> 
> And a similar issue (3y old): [Just-Some-Bots/MusicBot#1574](https://github.com/Just-Some-Bots/MusicBot/issues/1574)
> 
> It seems to be on their end.

> I'm not sure. But by the error code received we know that its a cloudflare issue.

I'm glad it's cloudflare's issue.   I actually intentionally bypass cloudflare for the our cloud IDE's services provided over websocket. Using cloudfare to proxy websocket is always troublesome for me. 


I found curl-websocket has this code too
```
curl-websocket.h:    CWS_CLOSE_REASON_GOING_AWAY           = 1001,
```
Both are 1001.  This is even more confusing.

**Comment by LucasMull** [comment]
This should have been addressed from my latest commits (handling reconnection).
