### ISSUE TITLE
add a new json path specifier for array

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#11]
For json array of the following form,
```
"abc": [  "a", "b", "c", 1, 2, 3 ]
```
It's better we can extract any elements from it with `json_scanf`.   In order to do this, we need a new path specifier to index the array's elements.  
Here is one proposal for the path specifier:  
```
json_scanf(str, "%d[abc][3]" ,&i); // get 1 and assign it to i. 
```

**Comment by LucasMull** [comment]
Ok, that works.

**Comment by mlite** [comment]
this is done in json_scanf2.
