### ISSUE TITLE
support json array in json-scanf

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#115]
Github API will return the following json array at the top level, 
```
[
{  "path": "file.rb",
  "mode": "100644",
  "type": "blob",
  "size": 30,
  "sha": "44b4fc6d56897b048c772eb4087f854f46256132",
  "url": "https://api.github.com/repos/octocat/Hello-World/git/blobs/44b4fc6d56897b048c772eb4087f854f46256132"
},
{
  "path": "subdir",
  "mode": "040000",
  "type": "tree",
  "sha": "f484d249c660418515fb01c2b9662073663c242e",
  "url": "https://api.github.com/repos/octocat/Hello-World/git/blobs/f484d249c660418515fb01c2b9662073663c242e"
},
{
  "path": "exec_file",
  "mode": "100755",
  "type": "blob",
  "size": 75,
  "sha": "45b983be36b73c0788dc9cbcb76cbb80fc7bb057",
  "url": "https://api.github.com/repos/octocat/Hello-World/git/blobs/45b983be36b73c0788dc9cbcb76cbb80fc7bb057"
}
]
```

json-scanf cannot handle this yet. we need to support de-serializing this array.

**Comment by mlite** [comment]
here is my proposal for json_scanf's array support.

Introduce a new format  "%A";  
```
    json_token * toks = NULL;
    //if the array object has no key and is the topest object like the above example:
    json_scanf(str, str_len, "[]%A",  &toks); 

   // if the array object has a key
   json_scanf(str, str_len, "[a]%A", &toks);

   // if the function succeeds toks is a null terminated array
   for (int i = 0;  toks[i]; i++)
       json_scanf(toks[i].start, toks[i].length, "...") // de-serializing each array element


```

**Comment by mlite** [comment]
@LucasMull can you please let me know what you think?

**Comment by LucasMull** [comment]
I really like this, way better than what I had in mind!

**Comment by LucasMull** [comment]
Using null terminated arrays will simplify our code too

**Comment by mlite** [comment]
Ok, I will implement this today.

**Comment by mlite** [comment]
There is a little revision to the proposal.   
```
// if the function succeeds,  toks is a null terminated array
    for (int i = 0;  toks[i].start; i++)
       json_scanf(toks[i].start, toks[i].length, "...") // de-serializing each array element
```
toks will be an array of tokens instead of array of token pointers, this will make the access of each token easier, we write
`toks[i].start` instead of `(toks[i]->start)`  and we can just `free (toks)` to reclaim the memory.

**Comment by mlite** [comment]
Ok, I have to back off to the original proposal because the revised design is error prone and less intuitive than null terminated array of pointers. 

Here is how it should work. 
```
   json_token ** toks = NULL;
    //if the array object has no key and is the topest object like the above example:
    json_scanf(str, str_len, "[]%A",  &toks); 

    // if the array object has a key
    json_scanf(str, str_len, "[a]%A", &toks);

    // if the function succeeds,  toks is a null terminated array of token pointer
    for (int i = 0;  toks[i]; i++)
       json_scanf(toks[i]->start, toks[i]->length, "...") // de-serializing each array element
```

**Comment by LucasMull** [comment]
Looks great! Awesome work. Just a question, how does the %F specifier works?

**Comment by mlite** [comment]
I propose we remove `%S`,  its goal can be achieved by using %T and memcpy.  I want to use `%S` for  json_printf for this special case:  if a string is null, we should print out null instead of "null"
```
json_printf("  |sha|:|%s| ", sha);   will print out   "sha": "null", this is wrong. 

json_printf("  |sha|:%S", sha);  will print out  "sha":null
```

**Comment by LucasMull** [comment]
> I propose we remove `%S` for json_scanf,  its goal can be achieved by using %T and memcpy.  I want to use `%S` for  json_printf for this special case:  if a string is null, we should print out null instead of "null"
> 
> ```
> 
> json_printf("  |sha|:|%s| ", sha);   // it will print out   "sha": "null", this is wrong. 
> 
> 
> 
> json_printf("  |sha|:%S", sha);     //  it will print out  "sha":null
> 
> ```
> 
> 

Sounds good. I don't think we will be needing the current %S any more after the introduction of %T.

**Comment by mlite** [comment]
this one is done.
