### ISSUE TITLE
reorder the json loading function signature to make the code easier to understand

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#131]
```
json_scanf(char * str, size_t len, ...);
json_snprintf(char * str, size_t len, ...);
json_load(void *p_guild, char *str, size_t len);   // this function signature has a different order of its parameters
```
If we  re-order all functions that are passed to user_agen::run to load json, as 

```
json_load(char * str, size_t len, void * p_build)
```

Then json_load will be easy to understand and can be reused for this case

```
json_scanf(str, len,  "[key]%F",  json_load,  p_guild);
```

**Comment by mlite** [comment]
If we follow the same parameter order for json de-serialization and serialization functions, we can improve the clarity of our code.

**Comment by LucasMull** [comment]
Really cool feature. I will fix it

**Comment by mlite** [comment]
This will touch many files. To avoid any merge difficulty caused by this change,  let's do in a schedule time so I will not make any changes or pushes. Please let me know when you want to make this change.

**Comment by mlite** [comment]
For this change, you can directly make changes in master branch and push it.  This will avoid any potential risk of merge conflict.
