### ISSUE TITLE
unifying the function pointer type for json de-serialization/serialization

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#135]
We need to pass function pointer to json_scanf/json_printf  to handle nested objects.  The function pointer type can be unified as one as shown in the following:
```
// extract data from str to stored in p, the return value is the number of data item extracted. 
int json_deserialization(char * str, size_t len, void *p)  

//  convert data pointed by p to str, the return value is the number of byte written to str. 
int json_serialization(char * str, size_t len, void * p) 
```

```
typedef    int (convert)(char * str, size_t, void *);
```

**Comment by mlite** [comment]
@LucasMull to give the context for this proposal, please look at how %F is used in json-scanf.c and json-printf.c

**Comment by stensalweb** [comment]
this is the same as what you have done.  After your change, we can define this  ```typedef    int (convert)(char * str, size_t, void *);` and use it for many places that we need to pass function pointers to handle nested object/array.

**Comment by stensalweb** [comment]
I marked as question for discussion.
