### ISSUE TITLE
use dati instead of data for type

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#136]
data is a very commonly used term in programming, it's easy to cause confusion.  I propose using dati (data in italian) instead of data. 

```
user::data  ->  user::dati
```
This can avoid confusion for the vest majority people except Italian.

**Comment by mlite** [comment]
@LucasMull what do you think?

**Comment by mlite** [comment]
@LucasMull @bchiu3  let me know if you have a better idea.

**Comment by LucasMull** [comment]
Sure I like that. I've seen it being used elsewhere too do its not an unfamiliar term
