### ISSUE TITLE
json_scanf2: the max number of nested paths and the max key length

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#14]
I propose to set up the above to max numbers:

1.  the max number of nested path :   8
2.  the max number of key length: 128

This function is designed to de-serialize data from rest API.  I expect most JSON data from rest API will not exceed the two limits.  But the two limits will simplify the memory management and reduce the number of malloc/free. 
Let me what do you think? 
I can make a change.

**Comment by LucasMull** [comment]
Yeah I find that pretty reasonable.

**Comment by mlite** [comment]
it is changed in 448df78.  we can always increase the values if it's necessary.
