### ISSUE TITLE
proposal to rename struct api_resbody_s

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#148]
`struct api_resbody_s` has been used a lot at different place,  using a meaningful and unique name will improve the clarity of our code. 

The following is the definition
```
struct api_resbody_s {
   char * str
   size_t size;
}
```

one name is `struct sized_buffer`

**Comment by mlite** [comment]
If we all agree this is a better name, @LucasMull  can you please rename it tomorrow when none else is changing the code at your time?

**Comment by LucasMull** [comment]
Of course! All agreed.

**Comment by bchiu3** [comment]
I also second this, api_resbody_s sounds too confusing.

**Comment by mlite** [comment]
Ok, let's change it to `struct sized_buffer` and remove `struct api_resbody_s` and `struct json_token`

**Comment by mlite** [comment]
```
struct sized_buffer {
   char * start;
   size_t  size;
}
``
