### ISSUE TITLE
Unimplemented method: MESSAGE_DELETE

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#15]
echo-bot exited with this after I deleted a message. 

```
	EVENT_DATA:	{"id":"797910163448791091","channel_id":"562694099887587340","guild_id":"562694099887587338"}
[discord-websockets.c:91] _discord_on_dispatch()
	ERROR:	Unimplemented GATEWAY_DISPATCH event: MESSAGE_DELETE
```

**Comment by mlite** [comment]
ERROR:  Unimplemented GATEWAY_DISPATCH event: MESSAGE_UPDATE

**Comment by mlite** [comment]
I just filed this issue to document the errors.

**Comment by LucasMull** [comment]
It will no longer abort the entire operation when detecting an not implemented event, but the user will still be notified about the missing implementation.
