### ISSUE TITLE
json_printf option to create fields dynamically

### ISSUE THREAD

**Issue by LucasMull** [cee-studio/orca#156]
To make json_printf more versatile, I propose the addition of specifiers that will print values by dereferencing a pointer, if the pointer is NULL then it should ignore printing the key/value pair altogether. EX:

```c
int num1 = 1, *num2 = NULL;
json_printf(str, len, 
    "|num1|:|%d|"
    "|num2|:|%pd|",
    num1, &num2);
```
In this example the resulting JSON would be:
```json
{"num1":1}
```
Because num2 is a NULL pointer that can't be dereferenced.

What do you think? @mlite

**Comment by PapauloGamerOfc** [comment]
If you want to prevent NULL pointers being ignored, you can also use assert.

**Comment by LucasMull** [comment]
#161 addresses this. Closing.

**Comment by mlite** [comment]
I will work on a more generic solution for this use case.

**Comment by LucasMull** [comment]
#194 solves this.
