### ISSUE TITLE
A tester bot

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#16]
The bot will read data or generate data randomly and send messages to a channel at a either predefined interval or random interval.

**Comment by mlite** [comment]
This will be used to automate the testing and can save our time down the road. It's worth doing it ASAP.  What do you think?

**Comment by LucasMull** [comment]
Once I fix a message fetching issue from the test branch I'll start working on it.

**Comment by mlite** [comment]
downgrade the priority. we have other high priority tasks to do.

**Comment by LucasMull** [comment]
@mlite Is this still necessary?

**Comment by mlite** [comment]
No. It turned out that this feature does not make sense.
