### ISSUE TITLE
organize our code to make it easy to navigate and build

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#162]
1. create a `bot` folder and move all bot code to this folder
2. create a `test` folder and move all test code to this folder
3. merge  `github.mk` and `discord.mk` to `Makefile`.

**Comment by mlite** [comment]
we still keep all library source code at the top-level.   @LucasMull Please let me know what you think?

**Comment by LucasMull** [comment]
Completely on board with this.

**Comment by mlite** [comment]
I have merged discord.mk, github.mk into Makefile.

**Comment by mlite** [comment]
it's done.
