### ISSUE TITLE
Rename orca to be unique and searchable 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#163]
Orca is a very popular word, searching Orca will bring up the killer whale orca.   There are two other popular C projects named Orca.   I propose we coin a unique spelling for our project. 

My proposal: Orka, Orkka,   Orkaa

Any other proposals? 

Implementation:  In order to bring existing users to the new repo,  we will create a new repo and link the current repo to the new one.

**Comment by PapauloGamerOfc** [comment]
Search "orka" on Google. For me, the whale still appears.

**Comment by mlite** [comment]
I think we need to rename it ASAP before it becomes more popular.    We will lost all stars after the renaming, we can create a new repo, don't delete this one.

**Comment by mlite** [comment]
What is Orca in portugal?

**Comment by LucasMull** [comment]
> What is Orca in portugal? 

Its the same unfortunately

**Comment by LucasMull** [comment]
> I think we need to rename it ASAP before it becomes more popular.    We will lost all stars after the renaming, we can create a new repo, don't delete this one. 
> 
> 

Can't we just rename this one?

**Comment by mlite** [comment]
Unfortunately, Orka Cloud is a product.  We need to find another name.

**Comment by LucasMull** [comment]
We can name it `killer dolphin`, thats what an orca basically is :)

**Comment by LucasMull** [comment]
Just kidding, this is hard.

**Comment by LucasMull** [comment]
Some keywords: Bot, API, REST, Communication, Multiplexing, Automation, Services
 
1. Botplex (kind of sound like a mattress brand)
2. MUXbot
3. Autoplex

I don't like any of those to be honest, but its good to do some brainstorming.

**Comment by bchiu3** [comment]
I think orca gives it an interesting name, but it isn't too unique. I think sticking the name to a keyword might be good, but it might not be memorizable or interesting. I don't really know of any other ideas though.

**Comment by mlite** [comment]
We need to hold on the renaming, orka is a register product for a computing cloud product.   We have to figure out a better an unique name.

**Comment by LucasMull** [comment]
Queen Ant: The vital piece of the colony. She breeds ants with various functions that work in harmony and maintain the colony alive. If the queen ant dies, the colony is doomed and dies off.(editado)

Maybe we could find some inspiration in the insect realm

**Comment by mlite** [comment]
Another candidate `Blueprint`

**Comment by LucasMull** [comment]
@mlite Is this still open for debate?

**Comment by mlite** [comment]
no, it's meaningless.  I will close it.
