### ISSUE TITLE
using of `sizeof(*new_message)` will reduce the clarity of the code

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#185]
For this code, ```dati *new_message = (dati*)calloc(1, sizeof *new_message);``` ,   one has to look at both the variable declaration and calloc to understand what is allocated. 

For
```
dati * new_message = (dati*)calloc(1, sizeof(dati))
```
it's much more obvious memory of one dati is allocated by just looking at `calloc`

**Comment by LucasMull** [comment]
Ok, I will do this change.
