### ISSUE TITLE
how jscon_scanf handle  null?

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#19]
given this example
```
str = {   "key1": null }


jscon_scanf(str, "%s[key1]", s);

printf ("%s\n", s); // what will this print out? 
```

**Comment by LucasMull** [comment]
It evokes a memset on the void ptr given as parameter, and uses the assigned specifier to know the memory size that must be set to 0.

```c

case 'n':/*CHECK FOR NULL*/
     {
        if (!STRNEQ(utils->buffer,"null",4))
            goto token_error; 

        Jscon_decode_null(&utils->buffer);

        /* null conversion */
        size_t n_bytes; /* get amount of bytes to be set to 0 */
        format_info(pair->specifier, &n_bytes);
        memset(pair->value, 0, n_bytes);
        return;
     }
```
`format_info()` will change `n_bytes` by the number of the expected bytes that memset should set to 0.

So to answer your question, if we want a string but encounter a null instead, we will end up with an empty string: "\0"

**Comment by mlite** [comment]
Ok, json_scanf2 does the same. I added more tests.  You can take a look.

**Comment by LucasMull** [comment]
Ok I will!

**Comment by LucasMull** [comment]
Great work on the json_scanf2! I added a few minor edits that I think may improve readability, and also some error checks.

With the question answered, I believe we can close this.
