### ISSUE TITLE
Add a section to README.md about how to build this repo in Windows without using WSL2

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#190]
We have users asking if this is supported on Windows.  Our current solution requires WSL2.  If you have successfully build this repo without using WSL2, the steps of building it will be valuable.  I was wondering if you (@PapauloGamerOfc) can add a section about this to README.md

**Comment by PapauloGamerOfc** [comment]
I will do this tomorrow.

**Comment by PapauloGamerOfc** [comment]
I'm doing this.

**Comment by PapauloGamerOfc** [comment]
https://github.com/cee-studio/orca/pull/200

**Comment by mlite** [comment]
Merged in https://github.com/cee-studio/orca/pull/200
