### ISSUE TITLE
implement %E for the existence of values

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#194]
If a struct has some fields that is undefined in a `json_scanf` call, we need to know which ones are.   We will capture the  recipients that are defined with `%E`.   The usage is like this
```
void ** e = NULL;  // to receive a ntl 
json_scanf(str, size, "[key1]%?s  [key2]%d  %E",  &val1, &val2,  &e);

for (int i = 0; e[i]; i++) {
    if (e[i] == &val)
       // key1 is defined
    if (e[i] == &val2)
       // key2 is defined
}

bool is_defined(void ** e, void * addr)  { 
     for (int i = 0; e[i]; i++) 
        if (e[i] == addr)  return true;
    
     return false;
}

free(e); // free the defined value ntl
```

**Comment by mlite** [comment]
@LucasMull Please take a look this proposal, let me what you think.

**Comment by LucasMull** [comment]
That works :) Looks like a very safe approach too, I like it.

**Comment by mlite** [comment]
This is done, but I will add some tests to demonstrate its usage.

**Comment by mlite** [comment]
`test-json-scanf-E.c` is added. @LucasMull can you please take a look the usage whenever you have time.  I have looked discord api. All field/key ending with a question mark will have to be checked if they are present or not.
