### ISSUE TITLE
Invalid Discord Gateway opcode (code: 7)

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#2]
I got this error after I started a second bot with the same token: 
```
[discord-websockets.c:132] _ws_on_text_cb()
    ERROR:    Invalid Discord Gateway opcode (code: 7)
Aborted
```
the first bot was killed by this error, the second one is still running.

**Comment by LucasMull** [comment]
You received a GATEWAY_RECONNECT (code 7), which is still unimplemented in our lib. But in this particular case we wouldn't want to attempt to reconnect because that will simply disconnect the seco d bot and start never ending reconnection attempts from both.

I'll make errors clearer for features that are detected, but are to be implemented.

See [Gateway Opcodes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-opcodes) for information.

**Comment by mlite** [comment]
The bot stopped with the same error.  This time, I didn't start the second bots.  
```
[discord-websockets.c:132] _ws_on_text_cb()
        ERROR:  Invalid Discord Gateway opcode (code: 7)
Aborted
```

Another question is how does a bot know whether it should reconnect or not.

**Comment by mlite** [comment]
I don't know the reason of this disconnect. This time.   Debugging networking code is hard.  Can we provide a function to log the stdout messages into a log file so we can look at it and figure out what happens?

**Comment by mlite** [comment]
This disconnection can be solved by an external monitoring service. If the bot process die, the external monitoring service just restart it.  This will simplify the code.

**Comment by LucasMull** [comment]
> I don't know the reason of this disconnection. Debugging networking code is hard.  Can we provide a function to log the stdout messages into a log file so we can look at it and figure out what happened? 

Of course. Should it be set by a function or as a -D flag?

**Comment by LucasMull** [comment]
> The bot stopped with the same error.  This time, I didn't start the second bot with the same token. 
> 
> ```
> 
> [discord-websockets.c:132] _ws_on_text_cb()
> 
>         ERROR:  Invalid Discord Gateway opcode (code: 7)
> 
> Aborted
> 
> ```
> 
> 
> 
> Another question is how does a bot know whether it should reconnect or not. 

Did the error happen when you activated the second bot?

To answer your question, Discord only provides is with the GATEWAY_RECONNECT trigger which should be responded with a GATEWAY_RESUME. But I don't think it provides us with any reason to why the disconnect happened.

**Comment by mlite** [comment]
> Did the error happen when you activated the second bot?

Not this time.

**Comment by LucasMull** [comment]
> > The bot stopped with the same error.  This time, I didn't start the second bot with the same token. 
> > 
> > ```
> > 
> > [discord-websockets.c:132] _ws_on_text_cb()
> > 
> >         ERROR:  Invalid Discord Gateway opcode (code: 7)
> > 
> > Aborted
> > 
> > ```
> > 
> > 
> > 
> > Another question is how does a bot know whether it should reconnect or not. 
> 
> Did the error happen when you activated the second bot?
> 
> To answer your question, Discord only provides us with the GATEWAY_RECONNECT trigger which should be responded with a GATEWAY_RESUME payload. But I don't think it provides any reason to why the disconnect happened, I will look to make sure.
> 

It does actually provide useful information that can be used to understand why the disconnect happened. It didn't show up because it aborts before it can trigger a on_close response, I will work on fixing that.

See: [Gateway Close Event Codes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes)

**Comment by mlite** [comment]
> To answer your question, Discord only provides us with the GATEWAY_RECONNECT trigger which should be responded with a GATEWAY_RESUME payload. But I don't think it provides any reason to why the disconnect happened, I will look to make sure.

Ok, if discord sends us "GATEWAY_RECONNECT",  then we need to  handle it in the code.

**Comment by mlite** [comment]
> > I don't know the reason of this disconnection. Debugging networking code is hard.  Can we provide a function to log the stdout messages into a log file so we can look at it and figure out what happened?
> 
> Of course. Should it be set by a function or as a -D flag?

It's better to make this behavior configurable by a configuration file (it can be json format).  Logging is very important for deamon/server code.  Normally, there are several level of logging: error, info, debug. 

the configuration can look like this: 
```
"logging" : {                                                                 
    "level": "debug", 
    "file" : {  
      "name" : "/var/log/a-test-bot.log",                                                 
      "append" : true
    }                                                                           
   },        
```

here is some c log libraries:
https://stackoverflow.com/questions/17741163/is-there-any-log-library-for-c-like-log4j-for-c

**Comment by mlite** [comment]
> > But I don't think it provides any reason to why the disconnect happened, I will look to make sure.
> 
> It does actually provide useful information that can help us understand why the disconnect happened. It didn't show up because the code aborts before triggering a on_close response, I will work on fixing that. I believe we would be dealing with error 4005.
> 
> See: [Gateway Close Event Codes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes)

Knowing the error code will be very helpful.  My two bots with different tokens were disconnected with GATEWAY_RECONNECT.

**Comment by mlite** [comment]
I will make change to use configuration file to set token and logging settings.

**Comment by LucasMull** [comment]
Alright, that will be really useful

**Comment by mlite** [comment]
I don't see this error anymore.
