### ISSUE TITLE
Being consistent in the coding style is great, but sometime we have a very good reason to deviate from it

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#208]
Here is one example:
```
struct perform_cbs cbs = {
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  };
```
The above does not bring any benefits. On the contrary, it will force people use smaller screens to scroll more.  The following is better. 
```
struct perform_cbs cbs = { 0 };
```

**Comment by LucasMull** [comment]
I completely agree! I did that because I was unsure if stensal-c will autoinitialize every field to 0. I will make the fix.
