### ISSUE TITLE
orka_strtoull needs to return 1 for success and 0 for failure. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#237]
The current definition:
```
void orka_strtoull(char *str, size_t len, void *p_data) 
```

json_scanf, %F is supposed to check if the conversion is successful or failed. 

the correct function signature should be 
```
int
orka_strtoull(char *str, size_t len, void *p_data);
```

**Comment by LucasMull** [comment]
Ok, will do the fix later
