### ISSUE TITLE
echo-bot existed with error

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#238]
```
[discord-websockets.cpp:477] ws_send_heartbeat()
        HEARTBEAT_PAYLOAD:
                {"op":1,"d":1}
[discord-websockets.cpp:298] ws_on_text_cb()
        ON_TEXT:
                {"t":null,"s":null,"op":11,"d":null}
        OP:             GATEWAY_HEARTBEAT_ACK
        EVENT_NAME:     NULL
        SEQ_NUMBER:     1
        EVENT_DATA:     null
[discord-websockets.cpp:341] ws_on_text_cb()
        PING: 93 ms
[http-common.c:236] perform_request()
        ERROR:  Assert Failed:  Error
        Expected:       CURLE_OK == ecode
Aborted
```

**Comment by LucasMull** [comment]
Really strange error which I assume not to be on our side. But we should be able to handle it

**Comment by LucasMull** [comment]
https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html
This may be useful.

**Comment by mlite** [comment]
Another error
```
[discord-websockets.cpp:361] ws_on_text_cb()
        ON_TEXT:
                {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-main-d8bm\",{\"micros\":0.0}]"]}}
        OP:             GATEWAY_HELLO
        EVENT_NAME:     NULL
        SEQ_NUMBER:     1
        EVENT_DATA:     {"heartbeat_interval":41250,"_trace":["[\"gateway-prd-main-d8bm\",{\"micros\":0.0}]"]}
[discord-websockets.cpp:111] ws_send_identify()
        ERROR:  Reach identify requests threshold (1 every 5 seconds)
Aborted
```

**Comment by LucasMull** [comment]
> Another error
> 
> ```
> [discord-websockets.cpp:361] ws_on_text_cb()
>         ON_TEXT:
>                 {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-main-d8bm\",{\"micros\":0.0}]"]}}
>         OP:             GATEWAY_HELLO
>         EVENT_NAME:     NULL
>         SEQ_NUMBER:     1
>         EVENT_DATA:     {"heartbeat_interval":41250,"_trace":["[\"gateway-prd-main-d8bm\",{\"micros\":0.0}]"]}
> [discord-websockets.cpp:111] ws_send_identify()
>         ERROR:  Reach identify requests threshold (1 every 5 seconds)
> Aborted
> ```

Did you try to run two bots with the same token in parallel?

**Comment by mlite** [comment]
No. They use different tokens.

**Comment by mlite** [comment]
I don't see the error again.
