### ISSUE TITLE
Make makefile less generic

### ISSUE THREAD

**Issue by LucasMull** [cee-studio/orca#247]
While having a generic Makefile makes it much more compact, it limits the versatility of our compilation. It might be better if we have the option to compile just the code that is necessary for what we're working on. For example, if I'm working on the reddit codebase it would make sense for me to do a simple `make reddit`. With that in mind, the`all` keyword could then  compile every possible API like so :
`all : common discord github reddit`

**Comment by mlite** [comment]
Ok, I will add these targets.

**Comment by mlite** [comment]
@LucasMull  merged in  15f36fd, please take a look if this what you want.

**Comment by mlite** [comment]
Please check if Makefile works for you, if yes, we can delete discord.mk

**Comment by LucasMull** [comment]
Works great!

**Comment by LucasMull** [comment]
I will be closing this now, thank you very much.
