### ISSUE TITLE
Get a dedicated channel on DiscordAPI server 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#27]
This is the requirement to get our lib into DiscordAPI server (which has more than 20k active developers) 

https://gist.github.com/meew0/bbbbd5348967dee5f7e84c0cd58983fd

We need to prioritize our implementation to meet the requirements.

**Comment by LucasMull** [comment]
I think we should start thinking how we will be implementing our API ratelimiting. Its a crucial feature.

**Comment by mlite** [comment]
The goal of getting to the server is to grow.   If there is a better way to grow and grow faster, we definitely should do that.  But it's worth keeping this list in mind when we prioritize our work.   Can you please file an issue for the API ratelimiting, so we don't forget it?

**Comment by mlite** [comment]
I will study the requirement and make them actionable items (issues)

**Comment by mlite** [comment]
> I think we should start thinking how we will be implementing our API ratelimiting. Its a crucial feature.

Thanks for explaining this to me. Could you please think about how to implement this?  
I will think about how to grow from a different perspective.

**Comment by LucasMull** [comment]
> > I think we should start thinking how we will be implementing our API ratelimiting. Its a crucial feature.
> 
> 
> 
> Thanks for explaining this to me. Could you please think about how to implement this?  
> 
> I will think about how to grow from a different perspective. 

I will start sketching asap

**Comment by mlite** [comment]
Let's work on this whenever there is no other higher priority issue. 

I want to get a weekly status for the following info:

How many APIs are left? 
How many API docs are left? 

Let's use doxygen to generate docs.

**Comment by LucasMull** [comment]
Got it. I will update the weekly status here every monday.

**Comment by LucasMull** [comment]
## Missing APIs:

### [Authentication](https://discord.com/developers/docs/reference#authentication)
- [ ] [Bearer Token Authentication](https://discord.com/developers/docs/reference#authentication-example-bearer-token-authorization-header)
### [Guild Resource](https://discord.com/developers/docs/resources/guild#guild-resource)
- [ ] [Get Guild Prune Count](https://discord.com/developers/docs/resources/guild#get-guild-prune-count)
- [ ] [Begin Guild Prune](https://discord.com/developers/docs/resources/guild#begin-guild-prune)
- [ ] [Get Guild Voice Regions](https://discord.com/developers/docs/resources/guild#get-guild-voice-regions)
- [ ] [Get Guild Invites](https://discord.com/developers/docs/resources/guild#get-guild-invites)
- [ ] [Get Guild Integrations](https://discord.com/developers/docs/resources/guild#get-guild-integrations)
- [ ] [Create Guild Integration](https://discord.com/developers/docs/resources/guild#create-guild-integration)
- [ ] [Modify Guild Integration](https://discord.com/developers/docs/resources/guild#modify-guild-integration)
- [ ] [Delete Guild Integration](https://discord.com/developers/docs/resources/guild#delete-guild-integration)
- [ ] [Sync Guild Integration](https://discord.com/developers/docs/resources/guild#sync-guild-integration)
- [ ] [Get Guild Widget Settings](https://discord.com/developers/docs/resources/guild#get-guild-widget-settings)
- [ ] [Modify Guild Widget](https://discord.com/developers/docs/resources/guild#modify-guild-widget)
- [ ] [Get Guild Widget](https://discord.com/developers/docs/resources/guild#get-guild-widget)
- [ ] [Get Guild Vanity URL](https://discord.com/developers/docs/resources/guild#get-guild-vanity-url)
- [ ] [Get Guild Widget Image](https://discord.com/developers/docs/resources/guild#get-guild-widget-image)
### [Template Resource](https://discord.com/developers/docs/resources/template#template-resource)
- [ ] [Get Template](https://discord.com/developers/docs/resources/template#get-template)
- [ ] [Create Guild from Template](https://discord.com/developers/docs/resources/template#create-guild-from-template)
- [ ] [Get Guild Templates](https://discord.com/developers/docs/resources/template#get-guild-templates)
- [ ] [Create Guild Templates](https://discord.com/developers/docs/resources/template#create-guild-template)
- [ ] [Sync Guild Template](https://discord.com/developers/docs/resources/template#sync-guild-template)
- [ ] [Modify Guild Template](https://discord.com/developers/docs/resources/template#modify-guild-template)
- [ ] [Delete Guild Template](https://discord.com/developers/docs/resources/template#delete-guild-template)
### [Webhook Resource](https://discord.com/developers/docs/resources/webhook#webhook-resource)
- [ ] [Create Webhook](https://discord.com/developers/docs/resources/webhook#create-webhook)
- [ ] [Get Channel Webhooks](https://discord.com/developers/docs/resources/webhook#get-channel-webhooks)
- [ ] [Get Guild Webhooks](https://discord.com/developers/docs/resources/webhook#get-guild-webhooks)
- [ ] [Get Webhook](https://discord.com/developers/docs/resources/webhook#get-webhook)
- [ ] [Get Webhook with Token](https://discord.com/developers/docs/resources/webhook#get-webhook-with-token)
- [ ] [Modify Webhook](https://discord.com/developers/docs/resources/webhook#modify-webhook)
- [ ] [Modify Webhook with Token](https://discord.com/developers/docs/resources/webhook#modify-webhook-with-token)
- [ ] [Delete Webhook](https://discord.com/developers/docs/resources/webhook#delete-webhook)
- [ ] [Delete Webhook with Token](https://discord.com/developers/docs/resources/webhook#delete-webhook-with-token)
- [ ] [Execute Webhook](https://discord.com/developers/docs/resources/webhook#execute-webhook)
- [ ] [Execute Slack-Compatible Webhook](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook)
- [ ] [Execute GitHub-Compatible Webhook](https://discord.com/developers/docs/resources/webhook#execute-githubcompatible-webhook)
- [ ] [Edit Webhook Message](https://discord.com/developers/docs/resources/webhook#edit-webhook-message)
- [ ] [Delete Webhook Message](https://discord.com/developers/docs/resources/webhook#delete-webhook-message)
### [Gateway](https://discord.com/developers/docs/topics/gateway)
- [ ] [Encoding and Compression](https://discord.com/developers/docs/topics/gateway#encoding-and-compression)
- [ ] [Caveats](https://discord.com/developers/docs/topics/gateway#caveats)
- [ ] [Tracking State](https://discord.com/developers/docs/topics/gateway#tracking-state)
- [ ] [Guild Subscriptions](https://discord.com/developers/docs/topics/gateway#guild-subscriptions)
- [ ] [Guild Availability](https://discord.com/developers/docs/topics/gateway#guild-availability)
- [ ] [Sharding](https://discord.com/developers/docs/topics/gateway#sharding)
- [ ] [Sharding for Very Large Bots](https://discord.com/developers/docs/topics/gateway#sharding-for-very-large-bots)
- [ ] [Commands and Events](https://discord.com/developers/docs/topics/gateway#commands-and-events)

**Comment by LucasMull** [comment]
@cee-studio/contributors
