### ISSUE TITLE
unsafe use of strcat in reqheader_init 

### ISSUE THREAD

**Issue by iwinulose** [cee-studio/orca#29]
reqheader_init uses strcat on untrusted data on discord-api.c:26

**Comment by stensalweb** [comment]
yep, a better design would be using 
```
n = snprintf( auth, MAX_HEADER_LEN, "Authorization: Bot  %s", token);`
ASSERT_S(n < MAX_HEADER_LEN, "out-of-bounds write of auth");
```

**Comment by mlite** [comment]
We should look at all strcat and replace them with safer `snprintf`

**Comment by mlite** [comment]
As a matter of fact,  `snprintf` is safer than `strscpy`

**Comment by LucasMull** [comment]
> reqheader_init uses strcat on untrusted data on discord-api.c:26

Nicely spotted I will work on fixing that.

**Comment by LucasMull** [comment]
> We should look at all `strcat` and replace them with safer `snprintf`

> As a matter of fact,  `snprintf` is safer than `strscpy` 

Shouldn't take too much effort to do. We can replace the internal `strscpy` code with a `snprintf` implementation, this will give a clearer intent I think. We can also create `strscat` on the same basis. This will give us the same expected functionality from those functions, but with the `snprintf` safety.

**Comment by LucasMull** [comment]
Really interesting read on the subject: https://developers.redhat.com/blog/2019/08/12/efficient-string-copying-and-concatenation-in-c/

For the time being we will go with the snprintf solution.

**Comment by mlite** [comment]
there is one problem of using `strscpy` and `strscat`, both are less well known.  To reduce the burden of learning both, the following pattern will easy to reason about.

```
n = snprintf(dest, len, "%s%s", s1, s2);
ASSERT_S(n < len, "oob of dest);  // this check cannot be omitted. 
```
dest cannot be overlapped with s1 or s2.
