### ISSUE TITLE
* SSL: EOF without close notify

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#3]
the bot stopped with this message.  It might be a reliability problem of bearssl.   We should use openssl, mbedtls or wolfssl which is more stable.

**Comment by LucasMull** [comment]
Yes, I also encountered this issue after leaving it running for a while, and couldn't find much information to why.


Am 08/01/2021 um 12:15 schrieb mlite <notifications@github.com>:

﻿

the bot stopped with this message. It might be a reliability problem of bearssl. We should use mbedtls which is more stable.

**Comment by mlite** [comment]
did you build your bot with stensal-c or gcc?

**Comment by mlite** [comment]
my bot is linked with bearssl not openssl.  If your bot is linked with openssl, then it's not  a problem of bearssl.  I need to look into this problem.

**Comment by LucasMull** [comment]
> did you build your bot with stensal-c or gcc? 

stensal-c with the -bearssl flag on, when compiling with gcc I deactivate this flag and never encountered this issue.

**Comment by mlite** [comment]
I will do more investigations.

**Comment by LucasMull** [comment]
I think its fair to assume this was a consequence of losing communication to Discord, since it only ever happened after a failed reconnection.
