### ISSUE TITLE
Improvement list

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#364]
Copied from Muller's comments:

1. We should have a websockets-common.c too, and have each callback be called on a different thread.
2. All structs from http-commons will be used together for every new API we deploy, it would make sense that we create a new struct that encompasses all these structs together, maybe call it struct http_common too
3. multipart/form-data will play an important role, as its a pretty common content type and most APIs will need to deal with it one way or another, so I should make it easier to implement multipart/form-data by creating http-common specific functions (but for that I will need to do the second one first, as I will need to store the curl_mime pointer inside the common struct)
4. Websockets should be able to deal with receiving and sending raw bytes data, curl-websockets already gives the option to receive/send data in raw bytes so it shouldn't be too hard to implement

**Comment by mlite** [comment]
Copied from Muller's comments:
I know some things that can be improved for http-commons.

**Comment by mlite** [comment]
The json-* building block has to be test more to make sure it's more reliable and less buggy.

**Comment by LucasMull** [comment]
I believe we address the unimplemented points in specific issues #575 #520, shall we close this?

**Comment by LucasMull** [comment]
Since I'm moving the remaining issues that are out of `orca` scope to `cee-utils`, I'll be closing this.
