### ISSUE TITLE
make self a part of  client

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#38]
```
void on_message(discord_t *client, discord_message_t *message)
{
  discord_user_t *self = discord_user_init();
  assert(NULL != self);

  discord_get_client_user(client, &self);
```
Can we only call `discord_get_client_user` once after `client` is initialized?  
This will certainly reduce the number of redundant calls, it might improve the reliability.

**Comment by LucasMull** [comment]
Yeah, pretty easy fix too. There's no reason for being called discord_get_user_client() over and over
