### ISSUE TITLE
support bot status/activity/links

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#387]
We need to add links to all bots we have built, it will be a free ads for our framework.

**Comment by mlite** [comment]
I mark it as priority one feature.

**Comment by mlite** [comment]
is this done?

**Comment by LucasMull** [comment]
Not completely, there are some fields that need ntl_realloc to work, so its not 100% done

**Comment by mlite** [comment]
Got it. thanks

**Comment by LucasMull** [comment]
This is done.
