### ISSUE TITLE
discord-common.h

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#39]
This file lists all very important size information. This is really great.  It must take a lot of time to find these limits.  I tried  to search them on discord, but I could not find them.  I was wondering if you can point out the link for me?

**Comment by mlite** [comment]
I found some of them. It really takes some time to find them. Great job.

**Comment by LucasMull** [comment]
Yeah, most of those limits are scattered throughout the Documentations and the Web. Its better than rely on dynamic sizes!

**Comment by LucasMull** [comment]
I think this can be closed.
