### ISSUE TITLE
Remove the build of shared lib and dynamic linking

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#4]
Dynamic lib and dynamic linking are good for the situations to avoid re-linking the executions for minor changes in the libraries. But it also increase the complexity of deployment (all shared libraries need to be deployed to the correct paths).   By linking everything statically, we can avoid the deployment complexity.  
@LucasMull   If you don't have objections, I will change the Makefile to remove the steps to build a shared lib.

**Comment by LucasMull** [comment]
Of course. No objections!
