### ISSUE TITLE
move all c files to common

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#404]
For all C files that do the heavy lifting work,  I propose to move them to common.   This will  improve the clarity of this project.

**Comment by mlite** [comment]
@LucasMull @bchiu3 please let me know what you think?  If you all agree, I will do the refactory tonight.

**Comment by LucasMull** [comment]
I'm 100% down with this!

**Comment by mlite** [comment]
I pushed a new branch: 
https://github.com/cee-studio/orca/tree/reorg

@LucasMull    Please test if you can build them, if yes, please merge them back to master.

**Comment by LucasMull** [comment]
Great, looks so much better. I will try compiling it tomorrow!

**Comment by LucasMull** [comment]
Building fine! Closing
