### ISSUE TITLE
merge json-comm.h with orka-debug.h

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#422]
VASSERT_S is only defined in orka-debug.h, but  ASSERT_S is defined in both json-common.h and orka-debug.h 

Should we merge them and only keep one?

**Comment by mlite** [comment]
I have to include "orka-debug.h" to json_scanf.c for creating better diagnostic messages. This causes redefine MACRO warnings as "json-common.h" is also included.  But removing "json-common.h" causes some compilation errors.

**Comment by LucasMull** [comment]
Ok, I will do the merge!

**Comment by LucasMull** [comment]
Done
