### ISSUE TITLE
We should hash sensitive stored data

### ISSUE THREAD

**Issue by lcsmuller** [cee-studio/orca#427]
Some data, such as bot token, are internally stored to be retrieved later on demand. Instead of storing the raw data we should hash then store it, and then unhash it when we need to apply it somewhere.

**Comment by mlite** [comment]
This is a premium feature. We need to have an option to enable/disable it in the configuration file:
```
token: {
   value: string
   hashed: bool
}
```

**Comment by mlite** [comment]
Downgrade the priority, don't see the need for it now.
