### ISSUE TITLE
Add an option to save response into a file and delete the file after from_json return. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#481]
We need an easy way to get json playload to debug from_json cb.  Here is one proposal:

1. Add an runtime option: can be enabled by the config file
2. If the option is on,  we save the HTTP response as a file before calling ok_cb
3. Once ok_cb returns, we delete the file. 
4. If ok_cb aborts, we can use this file to reproduce the problem.

**Comment by mlite** [comment]
This is my hack: https://github.com/cee-studio/orca/pull/485

**Comment by mlite** [comment]
@LucasMull  As we converting more dati definitions to  specs. We need a good way to debug errors.  This feature will be very helpful. Can you please prioritize it?

we can introduce a new field in to the configuration file
```
{
   "capture_data_before_response_cb": true/false
}
```

If this is enabled, we store the data like my hack, and delete it if the call back is not aborted. If this is disabled, we don't do anything.   To simplify the task, we can just use a global variable to enable/disable this.

**Comment by mlite** [comment]
@LucasMull  I can do this if you are busy with other things.

**Comment by LucasMull** [comment]
I can work on this, I will put the multithreading implementation aside for a while and do it.

**Comment by mlite** [comment]
dump.json works.  But this feature will still be valuable in the case of multi-threading.  I downgraded the priority.

**Comment by LucasMull** [comment]
I believe this is fully covered. @mlite

**Comment by mlite** [comment]
Yes, please close it
