### ISSUE TITLE
set longer timeouts for curl  

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#49]
This a special request for my builds that  are compiled with stensal-c.   Because my code are slower than normal, I was wondering if it's possible to expose the timeout options to the bot.config so we can set to longer values.

**Comment by LucasMull** [comment]
Does this cover it?

**Comment by LucasMull** [comment]
Do you still think this is necessary? @mlite

**Comment by mlite** [comment]
It seems not.  How about let’s  keep it open for another week?

**Comment by mlite** [comment]
it's not necessary anymore.  I have not seen any timeout errors.
