### ISSUE TITLE
rename main branch to perhaps lucas branch to avoid confusion. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#5]
It's easy to confuse main branch with master branch.   I suggest to rename it to something that is easy to identify. what do you think?

**Comment by LucasMull** [comment]
I agree!! How about DEV_branch or something of the sort?

**Comment by mlite** [comment]
if you are the only one uses it, you can use your name. If you think it's the branch that we all should merge our changes to first, yes, dev makes sense.

**Comment by LucasMull** [comment]
Ok let's go with `muller branch` then. Feels kinda weird using my first name!

**Comment by LucasMull** [comment]
Renamed my development branch to `muller_branch`
