### ISSUE TITLE
proposition to create json_printf() to circumvent the need of escaped commas

### ISSUE THREAD

**Issue by LucasMull** [cee-studio/orca#55]
We should create a new function json_printf(), that reads a string formatted in the likes of json_scanf() and write a json formatted string to a buffer as result. This will ensure readability when creating our own json strings, and consistency with the already existing json_scanf(). Here is an example:

```c
char buf[256];
json_printf(buf, sizeof(buf)-1, "[t][ta]%d, [k]%s", 4, "Hello There");
```
The expected string generated from this format is expected to be:
```json
{
    "t" : {
        "ta" : 4
    },
    "k" : "Hello There"
}
```

**Comment by mlite** [comment]
this is done in json-printf.c 
the above string can be escaped as
```
{
    |t| : {
        |ta| : 4
    },
    |k| : |Hello There|
}
```
