### ISSUE TITLE
Can be converted to specs

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#552]
```
1. (libdiscord.h:78-239) audit log (and its inner objects)   (specs/wip/audit_log.json)
2. (libdiscord.h:368-379) channel::message::get_list()
3. (libdiscord.h:382-406) channel::message::create()
4. (libdiscord.h:409-420) channel::message::edit()
5. (discord-common.h:338-421) identify object (and its inner objects)
```

**Comment by LucasMull** [comment]
MISSING CHANNEL FUNCTION SPECS

1. https://discord.com/developers/docs/resources/channel#modify-channel
2. https://discord.com/developers/docs/resources/channel#get-reactions
3. https://discord.com/developers/docs/resources/channel#bulk-delete-messages
4. https://discord.com/developers/docs/resources/channel#edit-channel-permissions
5. https://discord.com/developers/docs/resources/channel#create-channel-invite
6. https://discord.com/developers/docs/resources/channel#follow-news-channel
7. https://discord.com/developers/docs/resources/channel#group-dm-add-recipient

**Comment by LucasMull** [comment]
MISSING EMOJI FUNCTION SPECS

1. https://discord.com/developers/docs/resources/emoji#create-guild-emoji
2. https://discord.com/developers/docs/resources/emoji#modify-guild-emoji

**Comment by LucasMull** [comment]
MISSING GUILD FUNCTION SPECS

1. https://discord.com/developers/docs/resources/guild#create-guild
2. https://discord.com/developers/docs/resources/guild#modify-guild
3. https://discord.com/developers/docs/resources/guild#create-guild-channel
4. https://discord.com/developers/docs/resources/guild#modify-guild-channel-positions
5. https://discord.com/developers/docs/resources/guild#add-guild-member
6. https://discord.com/developers/docs/resources/guild#modify-current-user-nick
7. https://discord.com/developers/docs/resources/guild#modify-guild-role-positions
8. https://discord.com/developers/docs/resources/guild#modify-guild-role
9. https://discord.com/developers/docs/resources/guild#get-guild-prune-count
10. https://discord.com/developers/docs/resources/guild#begin-guild-prune
11. https://discord.com/developers/docs/resources/guild#create-guild-integration
12. https://discord.com/developers/docs/resources/guild#modify-guild-integration

**Comment by LucasMull** [comment]
MISSING TEMPLATE FUNCTION SPECS
1. https://discord.com/developers/docs/resources/template#create-guild-from-template
2. https://discord.com/developers/docs/resources/template#create-guild-template
3. https://discord.com/developers/docs/resources/template#modify-guild-template

**Comment by LucasMull** [comment]
MISSING USER FUNCTION SPECS
1. https://discord.com/developers/docs/resources/user#modify-current-user
2. https://discord.com/developers/docs/resources/user#modify-current-user
3. https://discord.com/developers/docs/resources/user#create-group-dm

**Comment by LucasMull** [comment]
MISSING WEBHOOK FUNCTION SPECS
1. https://discord.com/developers/docs/resources/webhook#create-webhook
2. https://discord.com/developers/docs/resources/webhook#modify-webhook
3. https://discord.com/developers/docs/resources/webhook#execute-webhook
4. https://discord.com/developers/docs/resources/webhook#edit-webhook-message

**Comment by mlite** [comment]
> MISSING CHANNEL FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/channel#modify-channel
> 2. https://discord.com/developers/docs/resources/channel#get-reactions
> 3. https://discord.com/developers/docs/resources/channel#bulk-delete-messages
> 4. https://discord.com/developers/docs/resources/channel#edit-channel-permissions
> 5. https://discord.com/developers/docs/resources/channel#create-channel-invite
> 6. https://discord.com/developers/docs/resources/channel#follow-news-channel
> 7. https://discord.com/developers/docs/resources/channel#group-dm-add-recipient

These are done

**Comment by mlite** [comment]
> MISSING TEMPLATE FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/template#create-guild-from-template
> 2. https://discord.com/developers/docs/resources/template#create-guild-template
> 3. https://discord.com/developers/docs/resources/template#modify-guild-template

These are done.

**Comment by mlite** [comment]
> MISSING EMOJI FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/emoji#create-guild-emoji
> 2. https://discord.com/developers/docs/resources/emoji#modify-guild-emoji

These are done

**Comment by mlite** [comment]
> MISSING TEMPLATE FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/template#create-guild-from-template
> 2. https://discord.com/developers/docs/resources/template#create-guild-template
> 3. https://discord.com/developers/docs/resources/template#modify-guild-template

These are done.

**Comment by mlite** [comment]
> MISSING USER FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/user#modify-current-user
> 2. https://discord.com/developers/docs/resources/user#modify-current-user
> 3. https://discord.com/developers/docs/resources/user#create-group-dm

Done

**Comment by mlite** [comment]
> MISSING USER FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/user#modify-current-user
> 2. https://discord.com/developers/docs/resources/user#modify-current-user
> 3. https://discord.com/developers/docs/resources/user#create-group-dm

Done

**Comment by mlite** [comment]
> MISSING WEBHOOK FUNCTION SPECS
> 
> 1. https://discord.com/developers/docs/resources/webhook#create-webhook
> 2. https://discord.com/developers/docs/resources/webhook#modify-webhook
> 3. https://discord.com/developers/docs/resources/webhook#execute-webhook
> 4. https://discord.com/developers/docs/resources/webhook#edit-webhook-message

Done

**Comment by LucasMull** [comment]
Awesome, thank you very much.

**Comment by mlite** [comment]
We will implement these based on the needs.

**Comment by LucasMull** [comment]
Every datatype we could cover currently has been covered.
