### ISSUE TITLE
Use "libdiscord.h" instead of <libdiscord.h> in all bots to support portable IDE settings better. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#570]
You can use #include "libdiscord.h" instead of using #include <libdiscord.h>, and use #include "common/orka-util.h" instead of #include <orka-util.h>.
This happens because "" searches also in the source path, but <> just searches the include path, like /usr/include, /usr/local/include and the include paths specified with -I.
If you do this, you won't even need to use -I./ or -Icommon.

**Comment by LucasMull** [comment]
Sorry, I've only seen this now. I'm okay with this, can you do it? @mlite

**Comment by mlite** [comment]
It should be easy. Please make the change whenever you want.

**Comment by mlite** [comment]
It seems it's not done yet. I will do it.

**Comment by LucasMull** [comment]
Sorry, I completely forgot. Thank you.
