### ISSUE TITLE
Implement json_parse()

### ISSUE THREAD

**Issue by LucasMull** [cee-studio/orca#571]
json_extract/json_inject are fantastic tools for wrapping the API, but sometimes we want a quick solution without needing to worry about every minute aspect, such as field name/type. json_parse will provide a quick solution with automatic conversion of types, and no need to create a special struct for wrapping around the JSON fields (assuming it returns its own specific datatype). I can easily do this since I already have the code ready from [JSCON](https://github.com/LucasMull/JSCON), I just need to simplify it and integrate jsmn to it.

Can you set a appropriate priority level for this @mlite ?

**Comment by mlite** [comment]
I do see the value of this pre-converted values.   This should be simple to implement. Please make sure the string values are escaped/unescaped properly.

**Comment by mlite** [comment]
I suggest treating string number as double, it's more consistent with how JavaScript treats number.  Whoever use this library can expect the same behavior as how Javascript behaviors.

**Comment by mlite** [comment]
I just found `double` cannot hold the value of `uint64_t` correctly.   Please consider using `long double` for json number.

**Comment by LucasMull** [comment]
This is done.
