### ISSUE TITLE
Accept SIGHUP to gracefully shutdown 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#578]
We need to have a way to exit `ws_run` infinite loop.   SIGNUP is the standard way to send a shutdown signal.   Once the signal is received, ws_run should exist from its infinite loop.  This will be useful for debugging memory leaks.

**Comment by LucasMull** [comment]
Wouldn't it be better to use SIGINT or SIGSTOP to exit the loop?

I'm asking this because its one of the two signals I'm aware to have a shortcut which can be easily sent

**Comment by mlite** [comment]
Very good points. What are the shortcuts?  We definitely want to use the easiest ones.

**Comment by LucasMull** [comment]
> Very good points. What are the shortcuts?  We definitely want to use the easiest ones. 

Ctrl-C (SIGINT)
Ctrl-Z (SIGSTOP)

**Comment by mlite** [comment]
Ctrl-Z

**Comment by LucasMull** [comment]
Alright!
