### ISSUE TITLE
Re-implement bot-quiz.cpp  with sqlite3

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#579]
Let's keep bot-quiz.cpp and re-implement bot-quiz2.cpp with sqlite3.   This will demonstrate how much we can simplify the code by properly using database.

**Comment by mlite** [comment]
Downgrade  the priority because we have other more important features.

**Comment by mlite** [comment]
I bump up the priority. This will help us build more content into bots.

**Comment by mlite** [comment]
I will do this.

**Comment by lcsmuller** [comment]
Closing for now, it can be revisited at a later time, or we can write a specific example bot that uses sqlite3 for simple caching
