### ISSUE TITLE
Need a function to delete n replies send by a bot

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#581]
Sometime bot's replies polluted the channel.   It will be handy of there is an API that we can delete n bot's replies in one call.

**Comment by mlite** [comment]
This will be useful for all bots.

**Comment by LucasMull** [comment]
https://discord.com/developers/docs/resources/channel#bulk-delete-messages

We will need to implement this, then its pretty straight-forward. Use channel::message::get_list() to get fetch messages, iterate through the list and for every message message whose author is the bot, we add it to the array of message_ids that will then be given as a parameter to channel::message::bulk_del()

**Comment by mlite** [comment]
Yes, this might work. I will work on this one.

**Comment by mlite** [comment]
We can delete all replies sent by a bot. We need to improve it so only people have the permissions to do the clean up.
