### ISSUE TITLE
Need a timer event-loop running in a separate thread

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#590]
This timer event-loop will pick up scheduled jobs in database and run them when the timer of each job runs out.   
One big problem of current bots is that the bot commands and bot replies are littered around in channels.  To mitigate this problem, many servers have to set up dedicated bot-spam channels for talking to bots.  This significantly limits the usability of bots.   If we have this timer event-loop, our bots can periodically clean up bot commands and bot replies.  Our bots can then be used at any channels.

**Comment by LucasMull** [comment]
Would it store every bot message id in the database, and once the event loop detects a schedule event it deleites every bot message from the database?

**Comment by mlite** [comment]
> Would it store every bot message id in the database, and once the event loop detects a schedule event it deletes every bot message fetched from database?

It will be too costly to do that.  We can just schedule jobs with predefined criteria for garbage collection or other things like this one https://www.reddit.com/r/discordapp/comments/m76s2u/is_there_a_bot_that_auto_disconnects_users_from/.  This is a very useful feature, and it's fun to implement.

**Comment by mlite** [comment]
The definition of garbage collection is very broad.  So this feature will be super useful and significantly improve the UX of bots.

**Comment by mlite** [comment]
This event-loop will not have connections with the websocket events

**Comment by LucasMull** [comment]
Got it. Looks fun, it won't be triggered by websockets event loop but I think it could be part of websockets. I believe setting a schedule callback would be pretty much like setting a event callback.

**Comment by mlite** [comment]
It should be independent of websocket.

**Comment by mlite** [comment]
Yes, it will be easier to implement if you use existing method to spawn the thread.  This event-loop could also be a child process forked from the main function.

**Comment by mlite** [comment]
This event-loop will only pick up jobs from database or a json file.  It will not communicate with other threads or the main process  thru other means.

**Comment by mlite** [comment]
I forgot the API rate limiting that complicates the situation. Please pick the easiest solution for you.

**Comment by LucasMull** [comment]
> I forgot the API rate limiting that complicates the situation. Please pick the easiest solution for you. 

Its okay it should still work, the requests are designe to work on any MT context, I've thought some more and I think its better to leave it outside websockets and be its own separate thing
