### ISSUE TITLE
study openAPI spec and write specs for Discord API endpoints

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#599]
We need to generate C functions for all Discord API endpoints by specs.  This work can be ported to support other rest APIs.

**Comment by mlite** [comment]
This task is to convert only endpoints to Open API specs.  We keep use our specs for data types.

**Comment by LucasMull** [comment]
I'll start working on it.

**Comment by LucasMull** [comment]
I propose using [openapi-generator](https://github.com/OpenAPITools/openapi-generator), we can wrap Orca to our own template written with [Mustache](https://mustache.github.io/mustache.5.html) and openapi-generator will do the rest for us. @mlite

**Comment by LucasMull** [comment]
We have no need for this in Discord API, as most of the endpoints have been covered already. This might make sense for other APIs that provide a OpenAPI specs such as Slack or GitHub
