### ISSUE TITLE
Unknown GATEWAY_DISPATCH event. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#6]
I pulled out the latest change, and got this error. 

```
[discord-websockets.c:83] _discord_on_dispatch()
        ERROR:  Unknown GATEWAY_DISPATCH event: MESSAGE_CREATE
Aborted
```

**Comment by LucasMull** [comment]
My bad, I was adjusting GATEWAY_DISPATCH event detectio. At the moment every event except `READY` will trigger that same error. It will be fixed.

**Comment by mlite** [comment]
It seems this one is fixed. If yes, please close it.
