### ISSUE TITLE
We need to implement the following Intents to be able to cache permission data

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#610]
Permission checks are needed for many operations.  If we implement the following intents, we can cache and update cached permission data. 

```
GUILDS (1 << 0)
  - GUILD_ROLE_CREATE
  - GUILD_ROLE_UPDATE
  - GUILD_ROLE_DELETE
  - CHANNEL_CREATE
  - CHANNEL_UPDATE

GUILD_MEMBERS (1 << 1)
  - GUILD_MEMBER_ADD
  - GUILD_MEMBER_UPDATE
  - GUILD_MEMBER_REMOVE

GUILD_BANS (1 << 2)
  - GUILD_BAN_ADD
  - GUILD_BAN_REMOVE
```

**Comment by mlite** [comment]
This one has higher priorities than other issues.

**Comment by mlite** [comment]
I have implemented the feature to cache data used to compute permissions.  We need to fully handle these events with callbacks now.

**Comment by LucasMull** [comment]
Closing, this is done: a904084
