### ISSUE TITLE
Support slash commands

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#616]
Here is one example of supporting slash command.

https://deno.com/deploy/docs/tutorial-discord-slash

It seems in order to do this, we need to integrate a web server

**Comment by mlite** [comment]
Another good choice is https://kore.io/

**Comment by mlite** [comment]
Most importantly, how to use gdb to debug each one of them.

**Comment by LucasMull** [comment]
This can't be properly supported until https://github.com/cee-studio/cee-utils/issues/17 is dealt with. This is because its still very experimental, and it seems the JSON provided by Discord doesn't always match the expected types outlined in their docs.
