### ISSUE TITLE
Runtime logging switch

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#617]
In the current design, we have to rebuild with `release=1` to disable all logging, and the built binary does not log anything anymore.   It's not convenient for trouble shooting problems in production.   We need to be able to enable/disable logging by changing the bot.config's logging level without rebuilding the code.

**Comment by mlite** [comment]
For example:
```
D_NOTOP_PRINT("UDP pack sent (%d bytes)", numbytes);
```
Should be enabled/disabled by the logging level of bot.config.

**Comment by mlite** [comment]
Here is a simple example: https://gist.github.com/fclairamb/7441750

**Comment by mlite** [comment]
Another one: https://github.com/rxi/log.c

**Comment by mlite** [comment]
We need to replace most of the compile time enabled logging with runtime enabled logging.

**Comment by LucasMull** [comment]
Alright, this makes a lot of sense, I will start working on this.

**Comment by LucasMull** [comment]
This is done.
