### ISSUE TITLE
No nullbyte character appended on struct discord message->content

### ISSUE THREAD

**Issue by Synth9283** [cee-studio/orca#634]
I found that there is no nullbyte character appended to `struct discord message->content` when you get it with `discord_get_channel_messages(client, message->channel_id, &params, &msgs);`. Here's how I found the bug when trying to implement a counter channel filter system:
```c
void on_message_create(struct discord *client, const struct discord_user *bot, const struct discord_message *message) {
    switch (message->channel_id) {
        case C_COUNTER: {
            size_t val = atoi((char*)message->content);
            if (val) {
                NTL_T(struct discord_message) msgs = NULL;
                struct discord_get_channel_messages_params params = {.limit = 2};
                discord_get_channel_messages(client, message->channel_id, &params, &msgs);
                if (!msgs) break;
                else {
                    // No nullbyte
                    size_t prev_val = atoi((char*)msgs[1]->content);
                    if (val-1 == prev_val) break;
                    else discord_delete_message(client, message->channel_id, message->id);
                }
            }
            else discord_delete_message(client, message->channel_id, message->id);
            break;
        }
        default: break;
    }
}
```

**Comment by mlite** [comment]
what is the value of `C_COUNTER`? 
How long is your message?

**Comment by Synth9283** [comment]
Just the channel id of the channel as an int literal as following. I tested it with various lengths but mostly 1-5
```c
#define C_COUNTER 800022514943655936
```

**Comment by mlite** [comment]
`connect` should be null terminated. Can you please use `log_info` to print out it's value?

**Comment by Synth9283** [comment]
Is that a function of some sort? I am unable to find `log_info`

**Comment by Synth9283** [comment]
I apologize, but may I ask how I can print with the `log_info` macro? I tried putting `content` as the argument, but I couldn't figure out how to get it to write to the stdout buffer

**Comment by LucasMull** [comment]
> I apologize, but may I ask how I can print with the `log_info` macro? I tried putting `content` as the argument, but I couldn't figure out how to get it to write to the stdout buffer

Do you have a bot.log file being generated after each execution? You can also edit bot.config and set "quiet" field to true in order to print logging information to your terminal!

**Comment by mlite** [comment]
> I apologize, but may I ask how I can print with the `log_info` macro? I tried putting `content` as the argument, but I couldn't figure out how to get it to write to the stdout buffer

log_info is just like the `printf` function, but it's for logging only.   You  use `fprintf(stderr,` too.

**Comment by Synth9283** [comment]
I dearly apologize, there was nothing wrong with `message->content`, it was just my code that was bad...

**Comment by LucasMull** [comment]
> I dearly apologize, there was nothing wrong with `message->content`, it was just my code that was bad...

Happens to the best of us lol! I'll be closing this one then

**Comment by mlite** [comment]
You can use strtol to do the conversation and use the 2nd parameter to check if the conversation is successful or not.

**Comment by Synth9283** [comment]
Thank you!
