### ISSUE TITLE
Implement SocketModeClient algorithm in our code. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#642]
https://github.com/slackapi/node-slack-sdk/blob/main/packages/socket-mode/src/SocketModeClient.ts

**Comment by LucasMull** [comment]
https://github.com/slack-go/slack/blob/master/socketmode/socket_mode_managed_conn.go

This is one easier to comprehend, and is somewhat similar to C in syntax

**Comment by LucasMull** [comment]
I believe this is done, some event listening is lacking but the structural part of the algorithm is there.
