### ISSUE TITLE
replicate better-sqlite3 in mujs

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#658]
https://github.com/JoshuaWise/better-sqlite3

**Comment by mlite** [comment]
Let's do this wrapper first.  It will significantly improve the development productivity for features that need db.

**Comment by mlite** [comment]
The test works well.   Can you make a repo just for this wrapper?  The wrapper will be used for other applications. 

We use the same method as cee-util to download  mujs  for this repo. 

I want to see code coverage for the test.

**Comment by LucasMull** [comment]
Sure, will we be downloading `mujs` from orca?

**Comment by mlite** [comment]
I think we can name this repo as  mujs-sqlite3
```

- mujs // will be downloaded like cee-utils
js_sqlite3.h
js_sqlite3.c
- test // the folder to host test code
```

**Comment by mlite** [comment]
BTW, please also wrap transaction.  we can just wrap
```
sqlite3_exec(db, "BEGIN TRANSACTION;", NULL, NULL, NULL);   ->    db.begin_transaction();
sqlite3_exec(db, "END TRANSACTION;", NULL, NULL, NULL);  --> db.end_transaction();
```

**Comment by LucasMull** [comment]
Ok got it!
