### ISSUE TITLE
Improve the readability of discord-public-user.c

### ISSUE THREAD

**Issue by stensalweb** [cee-studio/orca#66]
If  Discord_api_load_user  is moved to  discord-public-user.c,  The relation between discord_user_t  and the corresponding json string  will become clear. 

This applies to other Discord_api_load_xxx functions.

**Comment by LucasMull** [comment]
Yup that is reasonable. For "private" functions I like to give an idea of where they might be located, so I will rename them from Discord_api_load_xxxx to Discord_public_load_xxxx and move them to their appropriate files.
