### ISSUE TITLE
improve test-git2.c to fork a repo to a personal account

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#672]
In order to use test-git2.c, we have to manually fork a repo to our personal account.   It would be great if we can automate this step with `test-git2.c`

```
test-git2.c fork  git@github.com:cee-studio/orca.git
```
will fork the repo to our personal account.

**Comment by LucasMull** [comment]
Got it, I'll implement [Create Fork](https://docs.github.com/en/rest/reference/repos#create-a-fork)

**Comment by antropez** [comment]
Change of plans, I will be taking care of this endpoint.
