### ISSUE TITLE
Invalid discord invite links.

### ISSUE THREAD

**Issue by initial1ze** [cee-studio/orca#700]
Hey there, so I just came across this project and it piqued my interest but when I tried joining your discord server the invite was invalid/expired.

![Screenshot from 2021-09-23 11-03-13](https://user-images.githubusercontent.com/68731452/134458962-9ea6fbb0-9d2d-4011-a79f-f5c558b91b3d.png)

All the links provided are invalid.

- https://discord.gg/2jfycwXVM3  (https://github.com/cee-studio/orca/blob/master/README.md?plain=1#L11) (https://github.com/cee-studio/orca/blob/master/README.md?plain=1#L195)

- https://discord.gg/Q4Ub3wuF (https://github.com/cee-studio/orca/edit/master/docs/CONTRIBUTING.md?plain=1#L9)

I think it would be nice to have a single never expiring invite link rather than multiple ones.

**Comment by LucasMull** [comment]
I'm sorry, and thanks for letting us know! I will fix those, in the meantime you can join via this link: https://discord.gg/JjqTVehaY3
