### ISSUE TITLE
Add function naming convention to the coding guideline

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#79]
Should we add how static function, and private function, and public function should be named to the coding guideline?

**Comment by LucasMull** [comment]
Yes we should. Also should include how variables should be named

**Comment by LucasMull** [comment]
Because we settled with a data oriented approach heavily namespace reliant, I don't think we will be needing to distinguish between function types anymore. What do you think @mlite? Maybe we should do a namespace section instead.

**Comment by LucasMull** [comment]
I will be closing this.
