### ISSUE TITLE
Allocate api objects dynamically or statically?

### ISSUE THREAD

**Issue by LucasMull** [cee-studio/orca#8]
Should we allocate API objects statically? I'm not a fan of using triple pointers as a function parameter for fetching an array of objects.

Instead of:
```c
discord_guild_t *guild = discord_guild_init();
discord_user_t *user = discord_user_init();
discord_channel_t *channel = discord_channel_init();
```
we do
```c
discord_guild_t guild = {0}
discord_user_t user = {0}
discord_channel_t channel = {0}
```
But for
```c
discord_t *client = discord_init(token);
```
it remains the same

**Comment by mlite** [comment]
> Should we allocate API objects statically? I'm not a fan of using triple pointers as a function parameter for fetching an array of objects.
> 
> Instead of:
> 
> ```c
> discord_guild_t *guild = discord_guild_init();
> discord_user_t *user = discord_user_init();
> discord_channel_t *channel = discord_channel_init();
> ```
> 
> we do
> 
> ```c
> discord_guild_t guild = {0}
> discord_user_t user = {0}
> discord_channel_t channel = {0}
> ```
> 
> But for
> 
> ```c
> discord_t *client = discord_init(token);
> ```
> 
> it remains the same

For singleton objects, we can use static storage.   token will be a field of the settings object which will be  a singleton too.

**Comment by mlite** [comment]
```
static discord_guild_t guild = {0}
static discord_user_t user = {0}
static discord_channel_t channel = {0}
```
this will not take space for call stack.

**Comment by LucasMull** [comment]
We would use singletons for initialization then?

**Comment by mlite** [comment]
I need to read more of your code to fully understand the situation.

**Comment by mlite** [comment]
It won't affect the correctness.  It hasn't demonstrate the negative impact on our 3E design goal yet.   I would mark this as a low priority issue.
