### ISSUE TITLE
Improve the error message

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#83]
One user used an invalid token, and got the following message. 
```
[discord-api.c:268] perform_request()
    ERROR:    Unknown HTTP response code 401
Aborted (core dumped)
```

He didn't know how to fix the problem by reading this error.  Is it possible to improve the error message to "Unauthorized request, the probably cause: invalid bot token"? 
```
[discord-api.c:268] perform_request()
    ERROR:    401 Unauthorized, probably cause: invalid bot token
Aborted (core dumped)
```

**Comment by LucasMull** [comment]
That's a good suggestion, I will do that.
